### ISSUE TITLE
Guide: Collect Customer Satisfaction Scores (CSAT) from your customers in Slack

### ISSUE THREAD

**Issue by pmn** [aseriousbiz/abbot-docs-new#6]
CSAT, which stands for Customer Satisfaction Score, is a key metric used by companies to gauge customer contentment with a product, service, or interaction.  Abbot can help you collect CSAT from your customers in Slack via this simple Playbook: 

< playbook stuff >

**Comment by dahlbyk** [comment]
@pmn do you have a specific idea on what this Poll should do with its result? If not I'll just have it post the response to a Slack channel.
