### ISSUE TITLE
Guide: Alert your team about an unhappy customer in Slack

### ISSUE THREAD

**Issue by pmn** [aseriousbiz/abbot-docs-new#9]
Because Abbot is integrated with GPT-4, it can detect if a customer is unhappy in Slack. 

This guide shows you how to create a simple Playbook that is triggered when Abbot notices an unhappy customer.

**Comment by analogrelay** [comment]
I wrote a version of this as part of the Quick Start guide but I'll also refine it in to a guide of it's own.

**Comment by dahlbyk** [comment]
@pmn did you want to make https://docs.ab.bot/articles/playbooks/guides/alert-unhappy more NPS-centric or is it good for now?

**Comment by pmn** [comment]
I think it's good for now but that is a great idea.
